site: fzyyy0601's home page
title: Zoe's home page
greetings: Hi 👋
description: >-
  Welcome! Sit down, grab a cup of tea and let's start!
description_about: >-
  Hi, my name is Zoe. I am a full stack developer, a cs student. I like meeing new peopl, working out and making new stuff.
lang: en-US
timezone:  Europe/Rome
repo: https://github.com/fzyyy0601/fzyyy0601.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"
discus-identifier: powex # replace with your disqus shortname
comments-enabled: false # true to enable disqus comments, false to hide them

author:
  name: gesko
  bio: just a minimalist, personal blog
  userpicture: 
  username: # general username
  github: DavideBri # github username
  twitter: # twitter username
  mastodon: # mastodon profile (ex. mastodon.social/@my_username)
  linkedin: # linkedin profile
  email: fzy0531@gmail.com # email adress

# Font Settings
googlewebfonts: family=IBM+Plex+Mono:wght@100;200;300;400;500;600;700
# URL settings
url: "https://fzyyy0601.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


